packages:
  - '.'
  - '../../opentiny/genui-sdk/packages/core'
  - '../../opentiny/genui-sdk/packages/frameworks/react'
  - '../../opentiny/genui-sdk/packages/materials/react-antd'
  - '../../opentiny/genui-sdk/projects/tiny-schema-renderer-react'
allowBuilds:
  esbuild: set this to true or false
